CREATE TABLE IF NOT EXISTS "USERS"
(
    "USER_ID"  INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "EMAIL"    VARCHAR(20)                    NOT NULL,
    "LOGIN"    VARCHAR(20)                    NOT NULL,
    "NAME"     VARCHAR(20)                    NOT NULL,
    "BIRTHDAY" DATE                           NOT NULL
);

CREATE TABLE IF NOT EXISTS "FRIENDSHIP"
(
    "USER_ID"   INT     NOT NULL,
    "FRIEND_ID" INT     NOT NULL,
    "STATUS_ID" VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS "FILMS"
(
    "FILM_ID"      INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "NAME"         VARCHAR(20)                    NOT NULL,
    "DESCRIPTION"  VARCHAR(200)                   NOT NULL,
    "RELEASE_DATE" DATE                           NOT NULL,
    "DURATION"     INT                            NOT NULL
);

CREATE TABLE IF NOT EXISTS "FILM_GRADE_USERS"
(
    "FILM_ID" INT NOT NULL,
    "USER_ID" INT,
    "GRADES"  INT,
    CONSTRAINT "FK_FILM" FOREIGN KEY (FILM_ID)
        REFERENCES FILMS (FILM_ID)
        ON DELETE CASCADE,
    CONSTRAINT "FK_USER" FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS "FILM_RATING"
(
    "FILM_ID"   INT PRIMARY KEY NOT NULL,
    "RATING_ID" INT             NOT NULL,
    CONSTRAINT "FK_RATING" FOREIGN KEY (FILM_ID)
        REFERENCES FILMS (FILM_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "RATING"
(
    "RATING_ID" INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "NAME"      varchar(5)                     NOT NULL
);

CREATE TABLE IF NOT EXISTS "FILM_GENRE"
(
    "FILM_ID"  INT NOT NULL,
    "GENRE_ID" INT,
    CONSTRAINT "FK_GENRE" FOREIGN KEY (FILM_ID)
        REFERENCES FILMS (FILM_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "GENRES"
(
    "GENRE_ID" INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    "NAME"     VARCHAR(20)                    NOT NULL
);

ALTER TABLE "FILM_RATING"
    ADD FOREIGN KEY ("RATING_ID") REFERENCES "RATING" ("RATING_ID");

ALTER TABLE "FILM_GENRE"
    ADD FOREIGN KEY ("GENRE_ID") REFERENCES "GENRES" ("GENRE_ID");

ALTER TABLE "FILM_GRADE_USERS"
    ADD FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("USER_ID");

ALTER TABLE "FRIENDSHIP"
    ADD FOREIGN KEY ("USER_ID") REFERENCES "USERS" ("USER_ID");

ALTER TABLE "FRIENDSHIP"
    ADD FOREIGN KEY ("FRIEND_ID") REFERENCES "USERS" ("USER_ID");

